version: '3'
services:
  app:
    build: .
    image: porfolio
    mem_limit: 512m
    memswap_limit: 1024m 
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db  
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: porfolio
      MYSQL_USER: master
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: