name: Deploy on Master Merge

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Remove old Docker images
              run: docker image prune -af

            - name: Execute remote ssh and Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /srv/portfolio
                      sudo git pull origin master
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                      nvm use 22

                      sudo yarn install
                      sudo yarn migrate:prod
                      sudo yarn build

                      if pm2 describe portfolio > /dev/null 2>&1; then
                        pm2 restart portfolio
                      else
                        pm2 start "yarn start" --name portfolio
                      fi
