name: Deploy on Master Merge

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                path: node_modules
                key: node-modules-${{ hashFiles('yarn.lock') }}

            - name: Install dependencies
              run: yarn install

            - name: Set up Docker Compose
              uses: docker/compose-action@v2

            - name: Deploy with Docker Compose
              run: |
                  ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
                    cd /srv/porfolio
                    sudo git pull origin master
                    sudo docker-compose up -d --build
                  "
